### ISSUE TITLE
Corner cases not correctly handled.

### ISSUE THREAD

**Issue by Bismay5467** [alex-page/jamzone.today#10]
Hi there @alex-page 👋! I was looking through this project. I found the idea appealing and was studying the codebase. During the study I came across some issues : 

- `getTzOffset()` under the `index` file in the `utils` directory will return a `NaN` value if the offset is in the format HH : MM becoz the `NumberConstructor` will fail to work. This is not the expected outcome from this function.
- All the data in the `zones` router is obtained from the url search query. As all the values will be exposed to the user, if the user try to tinker with the values on the search query this may lead to the crashing of the router page or some errors. Hence I feel all the values obtained from the search query must be checked before working with those values. If any one of the required values is not right we may simply display an error page. 

I have a thorough understanding of your codebase. If the issues mentioned above are assigned to me I can fix them as I have all the skillsets required to solve those issues. However I am not much into frontend UI designing but if that is needed I can develop a great looking error page (obviously responsive) after some research and under the right guidance.

**Comment by alex-page** [comment]
Hey @Bismay5467 if you want to start with working on the issue with certain timezones getting cropped incorrectly that would be awesome.

**Comment by alex-page** [comment]
I am going to do some changes to move the data out of the URL params. So don't feel like that is something you have to work on right now.
