### ISSUE TITLE
BUG: Adding too many slots at once breaks the site

### ISSUE THREAD

**Issue by gwyneplaine** [alex-page/jamzone.today#2]
![21-30-7t602-a9spy](https://user-images.githubusercontent.com/12119389/220217696-1cd312f1-e861-46fe-8b8f-d50a16adf8eb.gif)

Reproduce:
* Keep adding items till it breaks.

**Comment by alex-page** [comment]
Should be fixed in [d2aba19](https://github.com/alex-page/jamzone.today/commit/d2aba197ba90cc6c0fa8622d41dbc8da5e06d517)
